title: Jacob Otiende # your name (or website title) here
logo: https://github.com/JacobOtiende/jacobotiende.github.io/raw/master/jacobpict.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  A graduate student specializing in Business Analytics and Artificial Intelligence 
  at The University of Texas at Dallas, I bring over three years of IT experience within the 
  Department of Defense to my academic journey. This unique background equips me with a solid foundation in 
  secure systems, data-driven decision-making, and the ability to tackle complex challenges in high-stakes environments.
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-o-otiende/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PDY54X40NK # your Google Analytics tracking ID here
